title: "Omar Guenoun's Blog"
author: "Omar Guenoun"
description: "Omar Guenoun's blog , posts about ML, Data and Finance" 

email: "guenounomar282@gmail.com"
github_username: "OGuenoun"
linkedin_username: "omar-guenoun"

theme: "minima"


kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
    tags: []

collections:
  pages:
    output: true
    permalink: /:name/

header_pages:
  - _pages/archive.md